
module.exports = {
    GROUP_PERMISSION:{
        READ_ODS_SCHEMA:"READ_ODS_SCHEMA",
        READ_BUSINESS_SCHEMA:"READ_BUSINESS_SCHEMA",
        WRITE_BUSINESS_SCHEMA:"WRITE_BUSINESS_SCHEMA",
        MODIFY_BUSINESS_SCHEMA:"MODIFY_BUSINESS_SCHEMA",
        SUBMIT_TASK:"SUBMIT_TASK"
    },
    DB_USAGE:{
        ODS:"ODS",
        BUSINESS:"BUSINESS",
        PRIVATE:"PRIVATE",
        TEMP:"TEMP"
    },
    TenantType:{
        PLATFORM:"PLATFORM",
        OUTER_SERVICE:"OUTER_SERVICE",
        GROUP_USER:"GROUP_USER",
        GLOBAL_ANALYST:"GLOBAL_ANALYST",
        GLOBAL_DEVELOPER:"GLOBAL_DEVELOPER"
    },
    TEMP_GROUP_ID : -1,
    StorageType:['HIVE','PHOENIX','ES'],
    HIVE_STORAGE_FORMAT:['ORC','TEXTFILE'],
    STORAGE_TYPE_OBJ:{
        "HIVE":"HIVE",
        "PHOENIX":"PHOENIX",
        "ES":"ES"
    },
}