
const USER_TYPE = {
     ADMIN:'ADMIN',
    USER:'USER'
}

const PAGE = "page";
const PAGE_DEFAULT = 1;
const SIZE = "size";
const SIZE_DEFAULT = 20;

const UPLOAD_MAX_SIZE = 10*1024*1024;
const UPLOAD_MAX_SIZE_TIP = "上传文件不能大于10M";


export { USER_TYPE ,PAGE,SIZE,PAGE_DEFAULT,SIZE_DEFAULT,UPLOAD_MAX_SIZE,UPLOAD_MAX_SIZE_TIP}
